domain: "https://discordbots.co.uk"
baseurl: ""
url: "https://discordbots.co.uk"
encoding: utf-8

include: 
  - '_pages'
  - '_pages/api'
  - '_pages/api/bots'
  - '_pages/api/servers'

sass:
  sass_dir: _sass
  style: compressed

collections:
  bots:
    output: true
    permalink: /:collection/:name/
  servers:
    output: true
    permalink: /servers/:name/

defaults:
  - scope:
      path: ""
      type: "bots"
    values:
      layout: "botpage"
  - scope:
      path: ""
      type: "servers"
    values:
      layout: "serverpage"
