domain: "https://discordfork.info"
baseurl: ""
url: "https://discordfork.info"
encoding: utf-8

include: ['_pages']

sass:
  sass_dir: _sass
  style: compressed

collections:
  bots:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "bots"
    values:
      layout: "botpage"
