categories:
  servers:
    pagename: Discord Serverlist
    add: Add your own server
    invite: Join this server
    parallax: /assets/images/background_servers.jpg
    description: The server list with built-in GitHub integration
  bots:
    pagename: Discord Botlist
    add: Add your own bot
    invite: Add this bot
    parallax: /assets/images/background_hongkong.jpg
    description: The botlist with built-in GitHub integration
